/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemimenaxhimitoraritprovimeve;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author GJKK
 */
public class OrariProvimeve extends javax.swing.JFrame {

    /**
     * Creates new form OrariProvimeve
     * 
     * 
     */
    Connection Con=null;
    PreparedStatement Pst=null;
    ResultSet Rs=null,Rs1=null;
    Statement St=null,St1=null;
    
    
    public OrariProvimeve() {
        initComponents();
        DisplayOrariProvimeve1();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrariProvimeveTable = new javax.swing.JTable();
        LogOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OrariProvimeveTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        OrariProvimeveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        OrariProvimeveTable.setRowHeight(28);
        OrariProvimeveTable.setSelectionBackground(new java.awt.Color(51, 0, 204));
        OrariProvimeveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrariProvimeveTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OrariProvimeveTable);

        LogOut.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        LogOut.setText("LogOut");
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOut)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOut))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void DisplayOrariProvimeve1(){
        try{
            Con=DriverManager.getConnection("jdbc:mysql://localhost:3308/sistemipërmenaxhimineoraritprovimeve","root","");
            St=Con.createStatement();
              LogInForm loginform= new LogInForm();
              JOptionPane.showMessageDialog(this,SistemiMenaxhimitOraritProvimeve.username);
//            Rs=St.executeQuery("Select * from OrariProvimeve");
              Rs1= St.executeQuery("Select  DepartamentiID from users  where uUsername='1'");
              Rs1.next();
              String departamenti=Rs1.getString("DepartamentiId");
              Rs=St.executeQuery("SELECT OrariProvimeve.OrariID,lënda.EmriLëndes, profesori.pEmri,profesori.pMbiemri,afati.AfatiEmri,OrariProvimeve.DataProvimit,departamenti.EmriDepartamentit,fakulteti.FakultetiEmri FROM ((((((OrariProvimeve INNER JOIN lënda ON OrariProvimeve.LëndaID = lënda.LëndaID) INNER JOIN profesori ON OrariProvimeve.ProfesoriID = profesori.ProfesoriID) INNER JOIN afati ON OrariProvimeve.AfatiID = afati.AfatiID)inner join departamenti on lënda.DepartamentiID=departamenti.DepartamentiID) inner join fakulteti on departamenti.FakultetiID=fakulteti.FakultetiID) inner join users on departamenti.DepartamentiID=users.DepartamentiID) where departamenti.DepartamentiID="+departamenti);
//            SELECT OrariProvimeve.OrariID,lënda.EmriLëndes, profesori.pEmri,afati.AfatiEmri
//            FROM (((OrariProvimeve
//            INNER JOIN lënda ON OrariProvimeve.LëndaID = lënda.LëndaID)
//            INNER JOIN profesori ON OrariProvimeve.ProfesoriID = profesori.ProfesoriID)
//            INNER JOIN afato ON OrariProvimeve.AfatiID = afati.AfatiID);
            OrariProvimeveTable.setModel(DbUtils.resultSetToTableModel(Rs));
        
        }catch(SQLException e){
        
        
        }
    }
    private void OrariProvimeveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrariProvimeveTableMouseClicked
        

    }//GEN-LAST:event_OrariProvimeveTableMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        new LogInForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrariProvimeve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrariProvimeve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrariProvimeve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrariProvimeve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrariProvimeve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOut;
    private javax.swing.JTable OrariProvimeveTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
